package View;

import Controller.CarsDAO;
import Model.Cars;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vang
 */
public class SearchCarFrm extends javax.swing.JFrame {

    private final String[] header = {"STT", "Biển số xe", "Tên chuyến", "Ngày đi", "Giờ đi", "Giá vé"};
    private ArrayList<Cars> items = new ArrayList<>();
    public static int maKhachHang;
    private int selectedIndex;
    DefaultTableModel table;

    public SearchCarFrm() {
        initComponents();
        setLocationRelativeTo(null);
        showComboData();
        String date1 = new SimpleDateFormat("yyyy-MM-dd").format(new Date().getTime());
        txtDate.setText(date1);
    }

    public void showComboData() {
        ArrayList<Cars> itemsCars = new ArrayList<>();
        itemsCars = new CarsDAO().getListItemName();
        for (Cars i : itemsCars) {
            conboNameCar.addItem(i.getName());
        }
    }

    public void ShowTable() {
        table.setRowCount(0);
        for (Cars i : items) {
            table.addRow(new Object[]{
                table.getRowCount() + 1, i.getNumber_car(), i.getName(), new SimpleDateFormat("yyyy-MM-dd").format(i.getDate()), i.getTime(), i.getPrice() + " VNĐ"
            });
        }
    }

    public void getMaKachHang(int id) {
        maKhachHang = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conboNameCar = new javax.swing.JComboBox();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKQTK = new javax.swing.JTable();
        txtDate = new javax.swing.JTextField();
        btnDatGhe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHoaDon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to our website");

        conboNameCar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblKQTK.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tblKQTK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblKQTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblKQTK.setAlignmentX(2.0F);
        tblKQTK.setAlignmentY(2.0F);
        tblKQTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKQTKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKQTK);

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnDatGhe.setText("Đặt Ghế");
        btnDatGhe.setEnabled(false);
        btnDatGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatGheActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("YYYY-MM-DD");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Chọn Chuyến Xe");

        btnHoaDon.setText("Hóa Đơn");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Tìm Kiếm Chuyến Xe");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conboNameCar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHoaDon))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(btnTimKiem)
                                .addGap(112, 202, Short.MAX_VALUE)
                                .addComponent(btnDatGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 100, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conboNameCar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(btnHoaDon)
                .addGap(44, 44, 44)
                .addComponent(btnDatGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String nameSearch = (String) conboNameCar.getSelectedItem();
        String date = null;
        if (!"".equals(txtDate.getText())) {
            Pattern pattern = Pattern.compile("[0-9]{4}\\-[0-9]{1,2}\\-[0-9]{1,2}");
            Matcher matcher = pattern.matcher(txtDate.getText());
            if(pattern.matcher(txtDate.getText()).matches()){
                date = txtDate.getText();
            }else{
                JOptionPane.showMessageDialog(this, "Nhập ngày tháng theo đúng định dạng yyyy-MM-dd");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ngày tháng không được để trống");
        }

        items = new CarsDAO().getListItemSearch(nameSearch, date);
        table = (DefaultTableModel) tblKQTK.getModel();
        table.setColumnIdentifiers(header);
        ShowTable();
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblKQTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKQTKMouseClicked
        btnDatGhe.setEnabled(true);
    }//GEN-LAST:event_tblKQTKMouseClicked

    private void btnDatGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatGheActionPerformed
        selectedIndex = tblKQTK.getSelectedRow();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "vui lòng chọn xe");

        } else {
            DatGhe form = new DatGhe();
            form.showDiemDon(items.get(selectedIndex), maKhachHang);
            form.showGhe((items.get(selectedIndex)));
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnDatGheActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        BillFrm billview = new BillFrm();
        billview.setVisible(true);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        LoginFrm view = new LoginFrm();
        view.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchCarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchCarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchCarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchCarFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatGhe;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox conboNameCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKQTK;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
